<a href="https://colab.research.google.com/github/SriRamK345/Numpy_lib/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy


In [ ]:
a = [2, 4, 6, 8, 10]
b = [1, 3, 5, 7, 9]
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
print(c)

[3, 7, 11, 15, 19]


In [ ]:
import numpy as np

In [ ]:
#range(start,stop,step)
range(0,5)
list(range(0,5))

[0, 1, 2, 3, 4]

In [ ]:
range(0,5,1)
list(range(0,5,2))

[0, 2, 4]

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [ ]:
mul = arr1 * arr2 # element wise multiplication
mul

array([ 6, 14, 24, 36, 50])

In [ ]:
np.array([3,5,4.4,2])

array([3. , 5. , 4.4, 2. ])

In [ ]:
np.array([1,3,4,6])

array([1, 3, 4, 6])

In [ ]:
np.array([1,3,4,6],dtype="float") ## dtype = float or int

array([1., 3., 4., 6.])

In [ ]:
np.array([[1,2,3.4,5.1,6]],dtype="int")

array([[1, 2, 3, 5, 6]])

In [ ]:
Var = [1,3,5,2.8]

In [ ]:
print(type(Var[0]))
# print(type(Var[1]))
# print(type(Var[2]))
print(type(Var[3]))

<class 'int'>
<class 'float'>


In [ ]:
np.zeros(5) # if one [ means one dimention

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5),dtype="int") # if one [[ means 2 dimention

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5,2),dtype="int") # (3)(5,2)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [ ]:
np.full(3,5)

array([5, 5, 5])

In [ ]:
np.full((3,5),5,dtype="float")

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(2,4,dtype="bool")

array([[ True, False, False, False],
       [False,  True, False, False]])

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# rand
np.random.rand(5) # this will create random number between 0 to 1

array([0.0705345 , 0.42950165, 0.99301961, 0.5146942 , 0.96772903])

In [ ]:
ran=np.random.rand(3,5)
ran

array([[0.02945104, 0.40044738, 0.75795409, 0.68305038, 0.59935727],
       [0.87193784, 0.00625475, 0.70488101, 0.8830848 , 0.31626919],
       [0.72900399, 0.55224996, 0.19795223, 0.66957682, 0.11483302]])

In [ ]:
# randn
np.random.randn(5) # this will create random number between -1 to 1

array([-0.93998096, -0.86875152, -0.6668452 ,  0.33824095, -0.50758587])

In [ ]:
#random.normal
#np.random.normal(loc=10,scale=2,size=(3,5)) # loc = mean and scale = standard deviation
np.random.normal(10,2,(3,5))

array([[10.76566551,  8.15997231,  6.14997916, 12.59069986, 11.44714644],
       [ 8.69968286,  9.3068495 , 12.80395083,  9.87577747,  7.93199634],
       [ 7.86457832, 12.45955245,  8.28827465, 13.82479355, 10.67303844]])

# randint

In [ ]:
np.random.randint(1,10,5) # this will create random number between 1 to 10

array([5, 8, 4, 9, 6])

In [5]:
x = np.random.randint(100, size=(5))
x

array([42,  8, 48,  6, 31])

In [6]:
# find the index where the value is 4

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [7]:
# find the indexes whare thye values are even

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [8]:
# index of 7

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr == 7)

print(x)

(array([6]),)


In [9]:
x = np.searchsorted(arr, 7)

print(x)

6


In [ ]:
np.random.randint(1,3,(3,5)) # this will create random number between 1 to 10

array([[2, 1, 1, 2, 2],
       [1, 1, 2, 1, 1],
       [1, 1, 2, 2, 2]])

In [ ]:
sample_array = np.random.randint(1,10,(3,5))
sample_array

array([[7, 1, 4, 6, 3],
       [8, 3, 1, 4, 7],
       [7, 6, 5, 1, 5]])

In [ ]:
sample_array.shape

(3, 5)

In [ ]:
sample_array.ndim  # to find the dimension of the array

2

In [ ]:
sample_array.dtype

dtype('int64')

In [ ]:
sample_array.size

15

In [ ]:
sample_array.reshape(5,3)

array([[7, 1, 4],
       [6, 3, 8],
       [3, 1, 4],
       [7, 7, 6],
       [5, 1, 5]])

In [ ]:
sample_array = np.arange(1,14)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
#np.reshape(sample_array,(3,4))  ## cannot reshape array of size 13 into shape (3,4)

In [ ]:
sample1 = np.random.randint(1,20,10)
sample1

array([ 3, 16,  9, 10, 17,  7,  5,  5, 12,  6])

In [ ]:
sample1.max() # to find max value in an array

17

In [ ]:
sample1.min() # to find min value in an array

3

In [ ]:
sample1.argmax() # to find index of max value in an array

4

In [ ]:
sample1.argmin() # to find index of min value in an array

0

In [ ]:
arr1 = np.arange(1,11)

In [ ]:
arr2 = np.arange(11,21)

In [ ]:
cont1 = np.concatenate((arr1,arr2))
cont1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr3 = np.random.randint(1,10,(3,5))
arr3

array([[6, 2, 3, 1, 5],
       [1, 7, 5, 1, 3],
       [6, 7, 5, 7, 4]])

In [ ]:
arr4 = np.random.randint(1,10,(3,5))
arr4

array([[1, 8, 8, 4, 6],
       [4, 6, 7, 2, 4],
       [8, 8, 4, 9, 4]])

In [ ]:
cont2 = np.concatenate((arr3,arr4))
cont2

array([[6, 2, 3, 1, 5],
       [1, 7, 5, 1, 3],
       [6, 7, 5, 7, 4],
       [1, 8, 8, 4, 6],
       [4, 6, 7, 2, 4],
       [8, 8, 4, 9, 4]])

In [ ]:
cont3 = np.concatenate((arr3,arr4),axis=1)
cont3

array([[6, 2, 3, 1, 5, 1, 8, 8, 4, 6],
       [1, 7, 5, 1, 3, 4, 6, 7, 2, 4],
       [6, 7, 5, 7, 4, 8, 8, 4, 9, 4]])

In [ ]:
arr5 = np.array([1,2,3,22,44,55,3,32,2,1])
arr5

array([ 1,  2,  3, 22, 44, 55,  3, 32,  2,  1])

In [ ]:
np.split(arr5,[3,5])

[array([1, 2, 3]), array([22, 44]), array([55,  3, 32,  2,  1])]

In [ ]:
x,y,z = np.split(arr5,[3,5])

In [ ]:
print(x)
print(y)
print(z)

[1 2 3]
[22 44]
[55  3 32  2  1]


In [ ]:
arr6 = np.arange(1,31).reshape(6,5)
arr6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
np.split(arr6,[1,5])

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30]])]

In [ ]:
 np.vsplit(arr6,[1,5])

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30]])]

In [ ]:
a,b,c = np.hsplit(arr6,[1,3])

In [ ]:
print(a)
print(b)
print(c)

[[ 1]
 [ 6]
 [11]
 [16]
 [21]
 [26]]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]
 [27 28]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]
 [29 30]]


In [ ]:
arr7 = np.array([1,6,22,34,334,54,56])

In [ ]:
np.sort(arr7)

array([  1,   6,  22,  34,  54,  56, 334])

In [ ]:
ran1=np.random.normal(10,2,(3,5))
ran1

array([[ 9.01978607, 11.39057839,  7.65054019,  6.77795166, 11.125336  ],
       [ 9.32379863,  9.83245046,  9.17876189, 11.77747319, 12.50320881],
       [ 9.56334174,  6.6158182 , 13.76724569, 11.79562003, 11.90435809]])

In [ ]:
np.sort(ran1,axis=0)

array([[ 9.01978607,  6.6158182 ,  7.65054019,  6.77795166, 11.125336  ],
       [ 9.32379863,  9.83245046,  9.17876189, 11.77747319, 11.90435809],
       [ 9.56334174, 11.39057839, 13.76724569, 11.79562003, 12.50320881]])

In [ ]:
np.sort(ran1,axis=1)

array([[ 6.77795166,  7.65054019,  9.01978607, 11.125336  , 11.39057839],
       [ 9.17876189,  9.32379863,  9.83245046, 11.77747319, 12.50320881],
       [ 6.6158182 ,  9.56334174, 11.79562003, 11.90435809, 13.76724569]])

In [ ]:
arr7 = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr7

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr7[0,0]  # indexing

5

In [ ]:
arr7[2,1]

40

In [ ]:
#slicing
arr7

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr7[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [ ]:
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr2[2::4] # [start:stop:step]

array([13, 17])

In [ ]:
arr8 = np.arange(1,31).reshape(5,6)
arr8

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr8[1:4,0:5]

array([[ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [ ]:
arr8[0::2,0::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [ ]:
arr8[0::2,0:3]

array([[ 1,  2,  3],
       [13, 14, 15],
       [25, 26, 27]])

In [ ]:
arr8[0::2,0::2] = 99
arr8

array([[99,  2, 99,  4, 99,  6],
       [ 7,  8,  9, 10, 11, 12],
       [99, 14, 99, 16, 99, 18],
       [19, 20, 21, 22, 23, 24],
       [99, 26, 99, 28, 99, 30]])

In [ ]:
ex = np.arange(1,26).reshape(5,5)
ex

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ex[[0,4],[2,4]] #[row1,row2],[col1,col2]

array([ 3, 25])

In [ ]:
# conditional operators
ex > 10 # > , < , & , <= , >=

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
ex[ex>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
ex /ex # Arithematic operation

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ex - 10 # substraction

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
samp = np.arange(1,11)
samp

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sqrt(samp)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
np.exp(samp)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [ ]:
np.log(samp)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [ ]:
np.subtract(samp,5)

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [ ]:
np.mean(samp) # Statical operations

5.5

In [ ]:
np.median(samp)

5.5

In [ ]:
# secondary degree equstions
# 2X1 + X2 = 5
# -3X2 + 6X2 = 0

In [ ]:
Coeffi = np.array([[2,1],[-3,6]])
Coeffi

array([[ 2,  1],
       [-3,  6]])

In [ ]:
Output = np.array([5,0])
Output

array([5, 0])

In [ ]:
np.linalg.solve(Coeffi,Output)

array([2., 1.])

## intersect1d

In [ ]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

In [ ]:
np.intersect1d(n1,n2) # commom elements

array([50, 60])

In [ ]:
np.setdiff1d(n1,n2) # elements in n1 but not in n2

array([10, 20, 30, 40])

In [ ]:
np.setdiff1d(n2,n1) # elements in n2 but not in n1

array([70, 80, 90])

## addition of numpy array

In [ ]:
n1 = np.array([10,20])
n2 = np.array([30,40])

In [ ]:
np.sum([n1,n2])

100