<a href="https://colab.research.google.com/github/SriRamK345/Numpy_lib/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [6]:
mul = arr1 * arr2
mul

array([ 6, 14, 24, 36, 50])

In [7]:
np.array([3,5,4.4,2])

array([3. , 5. , 4.4, 2. ])

In [8]:
np.array([1,3,4,6])

array([1, 3, 4, 6])

In [13]:
np.array([1,3,4,6],dtype="float") ## dtype = float or int

array([1., 3., 4., 6.])

In [14]:
np.array([[1,2,3.4,5.1,6]],dtype="int")

array([[1, 2, 3, 5, 6]])

In [11]:
Var = [1,3,5,2.8]

In [12]:
print(type(Var[0]))
# print(type(Var[1]))
# print(type(Var[2]))
print(type(Var[3]))

<class 'int'>
<class 'float'>


In [2]:
np.zeros(5) # if one [ means one dimention

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3,5),dtype="int") # if one [[ means 2 dimention

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np