<a href="https://colab.research.google.com/github/SriRamK345/Numpy_lib/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = [2, 4, 6, 8, 10]
b = [1, 3, 5, 7, 9]
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
print(c)

[3, 7, 11, 15, 19]


In [2]:
import numpy as np

In [3]:
#range(start,stop,step)
range(0,5)
list(range(0,5))

[0, 1, 2, 3, 4]

In [4]:
range(0,5,1)
list(range(0,5,2))

[0, 2, 4]

In [5]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [6]:
mul = arr1 * arr2 # element wise multiplication
mul

array([ 6, 14, 24, 36, 50])

In [7]:
np.array([3,5,4.4,2])

array([3. , 5. , 4.4, 2. ])

In [8]:
np.array([1,3,4,6])

array([1, 3, 4, 6])

In [9]:
np.array([1,3,4,6],dtype="float") ## dtype = float or int

array([1., 3., 4., 6.])

In [10]:
np.array([[1,2,3.4,5.1,6]],dtype="int")

array([[1, 2, 3, 5, 6]])

In [11]:
Var = [1,3,5,2.8]

In [12]:
print(type(Var[0]))
# print(type(Var[1]))
# print(type(Var[2]))
print(type(Var[3]))

<class 'int'>
<class 'float'>


In [13]:
np.zeros(5) # if one [ means one dimention

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,5),dtype="int") # if one [[ means 2 dimention

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,5,2),dtype="int") # (3)(5,2)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [18]:
np.full(3,5)

array([5, 5, 5])

In [20]:
np.full((3,5),5,dtype="float")

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(2,4,dtype="bool")

array([[ True, False, False, False],
       [False,  True, False, False]])

In [23]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
# rand
np.random.rand(5) # this will create random number between 0 to 1

array([0.95667356, 0.54433394, 0.92121115, 0.20499294, 0.33749387])

In [106]:
ran=np.random.rand(3,5)
ran

array([[0.0201968 , 0.75844691, 0.30733978, 0.93077069, 0.26279535],
       [0.94091073, 0.12854248, 0.83883278, 0.27920045, 0.07088307],
       [0.91933214, 0.26232074, 0.40882695, 0.11013511, 0.49594522]])

In [105]:
# randn
np.random.randn(5) # this will create random number between -1 to 1

array([ 0.80451242,  1.78925785, -1.02551996,  0.11404729,  1.11552415])

In [31]:
#random.normal
#np.random.normal(loc=10,scale=2,size=(3,5)) # loc = mean and scale = standard deviation
np.random.normal(10,2,(3,5))

array([[10.16544856, 10.70272154, 14.09280148,  9.97204625, 10.67492767],
       [11.00312838, 10.74188095,  6.7295255 ,  9.93377843, 13.22234685],
       [10.31418038,  7.97042708,  7.82411595,  9.54227316,  8.54205236]])

In [34]:
# randint
np.random.randint(1,10,5) # this will create random number between 1 to 10

array([3, 6, 3, 1, 2])

In [36]:
np.random.randint(1,3,(3,5)) # this will create random number between 1 to 10

array([[2, 1, 1, 2, 2],
       [1, 2, 1, 1, 2],
       [1, 1, 2, 2, 2]])

In [44]:
sample_array = np.random.randint(1,10,(3,5))
sample_array

array([[4, 6, 7, 5, 9],
       [5, 5, 6, 8, 9],
       [5, 4, 5, 4, 5]])

In [45]:
sample_array.shape

(3, 5)

In [47]:
sample_array.ndim  # to find the dimension of the array

2

In [48]:
sample_array.dtype

dtype('int64')

In [49]:
sample_array.size

15

In [50]:
sample_array.reshape(5,3)

array([[4, 6, 7],
       [5, 9, 5],
       [5, 6, 8],
       [9, 5, 4],
       [5, 4, 5]])

In [53]:
sample_array = np.arange(1,14)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [54]:
#np.reshape(sample_array,(3,4))  ## cannot reshape array of size 13 into shape (3,4)

ValueError: cannot reshape array of size 13 into shape (3,4)

In [56]:
sample1 = np.random.randint(1,20,10)
sample1

array([11,  2,  1,  7, 11,  4,  2, 10,  8, 15])

In [57]:
sample1.max() # to find max value in an array

15

In [58]:
sample1.min() # to find min value in an array

1

In [59]:
sample1.argmax() # to find index of max value in an array

9

In [60]:
sample1.argmin() # to find index of min value in an array

2

In [63]:
arr1 = np.arange(1,11)

In [64]:
arr2 = np.arange(11,21)

In [65]:
cont1 = np.concatenate((arr1,arr2))
cont1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
arr3 = np.random.randint(1,10,(3,5))
arr3

array([[1, 1, 5, 1, 3],
       [9, 8, 6, 5, 5],
       [9, 1, 5, 5, 8]])

In [67]:
arr4 = np.random.randint(1,10,(3,5))
arr4

array([[4, 1, 7, 2, 7],
       [5, 1, 7, 2, 6],
       [3, 2, 4, 1, 7]])

In [68]:
cont2 = np.concatenate((arr3,arr4))
cont2

array([[1, 1, 5, 1, 3],
       [9, 8, 6, 5, 5],
       [9, 1, 5, 5, 8],
       [4, 1, 7, 2, 7],
       [5, 1, 7, 2, 6],
       [3, 2, 4, 1, 7]])

In [69]:
cont3 = np.concatenate((arr3,arr4),axis=1)
cont3

array([[1, 1, 5, 1, 3, 4, 1, 7, 2, 7],
       [9, 8, 6, 5, 5, 5, 1, 7, 2, 6],
       [9, 1, 5, 5, 8, 3, 2, 4, 1, 7]])

In [77]:
arr5 = np.array([1,2,3,22,44,55,3,32,2,1])
arr5

array([ 1,  2,  3, 22, 44, 55,  3, 32,  2,  1])

In [78]:
np.split(arr5,[3,5])

[array([1, 2, 3]), array([22, 44]), array([55,  3, 32,  2,  1])]

In [80]:
x,y,z = np.split(arr5,[3,5])

In [81]:
print(x)
print(y)
print(z)

[1 2 3]
[22 44]
[55  3 32  2  1]


In [103]:
arr6 = np.arange(1,31).reshape(6,5)
arr6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [88]:
np.split(arr6,[1,5])

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30]])]

In [89]:
 np.vsplit(arr6,[1,5])

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30]])]

In [93]:
a,b,c = np.hsplit(arr6,[1,3])

In [94]:
print(a)
print(b)
print(c)

[[ 1]
 [ 6]
 [11]
 [16]
 [21]
 [26]]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]
 [27 28]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]
 [29 30]]


In [97]:
arr7 = np.array([1,6,22,34,334,54,56])

In [98]:
np.sort(arr7)

array([  1,   6,  22,  34,  54,  56, 334])

In [120]:
ran1=np.random.normal(10,2,(3,5))
ran1

array([[ 9.58094543,  9.91215843, 11.22525834, 10.93048889, 11.50637743],
       [10.73115175, 12.61244954, 10.00375448,  8.52361919, 11.04449981],
       [10.07355393,  8.60427658,  9.63812145,  9.73540597,  5.731671  ]])

In [111]:
np.sort(ran1,axis=0)

array([[ 7.88441241,  6.37060541,  9.90154747,  9.97498039,  6.94460351],
       [ 9.36322947,  9.1142068 , 12.08539809, 10.24386393,  7.0709955 ],
       [12.92025345,  9.47869991, 12.55482029, 11.33756107,  7.70209411]])

In [112]:
np.sort(ran1,axis=1)

array([[ 6.37060541,  7.0709955 , 11.33756107, 12.55482029, 12.92025345],
       [ 6.94460351,  7.88441241,  9.1142068 , 10.24386393, 12.08539809],
       [ 7.70209411,  9.36322947,  9.47869991,  9.90154747,  9.97498039]])