<a href="https://colab.research.google.com/github/SriRamK345/Numpy_lib/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = [2, 4, 6, 8, 10]
b = [1, 3, 5, 7, 9]
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
print(c)

[3, 7, 11, 15, 19]


In [2]:
import numpy as np

In [3]:
#range(start,stop,step)
range(0,5)
list(range(0,5))

[0, 1, 2, 3, 4]

In [4]:
range(0,5,1)
list(range(0,5,2))

[0, 2, 4]

In [5]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [6]:
mul = arr1 * arr2 # element wise multiplication
mul

array([ 6, 14, 24, 36, 50])

In [7]:
np.array([3,5,4.4,2])

array([3. , 5. , 4.4, 2. ])

In [8]:
np.array([1,3,4,6])

array([1, 3, 4, 6])

In [9]:
np.array([1,3,4,6],dtype="float") ## dtype = float or int

array([1., 3., 4., 6.])

In [10]:
np.array([[1,2,3.4,5.1,6]],dtype="int")

array([[1, 2, 3, 5, 6]])

In [11]:
Var = [1,3,5,2.8]

In [12]:
print(type(Var[0]))
# print(type(Var[1]))
# print(type(Var[2]))
print(type(Var[3]))

<class 'int'>
<class 'float'>


In [13]:
np.zeros(5) # if one [ means one dimention

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,5),dtype="int") # if one [[ means 2 dimention

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,5,2),dtype="int") # (3)(5,2)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [18]:
np.full(3,5)

array([5, 5, 5])

In [20]:
np.full((3,5),5,dtype="float")

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(2,4,dtype="bool")

array([[ True, False, False, False],
       [False,  True, False, False]])

In [23]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
# rand
np.random.rand(5) # this will create random number between 0 to 1

array([0.95667356, 0.54433394, 0.92121115, 0.20499294, 0.33749387])

In [27]:
np.random.rand(3,5)

array([[0.26068353, 0.00752331, 0.51866794, 0.80389331, 0.23823909],
       [0.64722189, 0.1443949 , 0.71623581, 0.74544617, 0.82735065],
       [0.84829166, 0.66182796, 0.39116818, 0.27352051, 0.05166157]])

In [26]:
# randn
np.random.randn(5) # this will create random number between -1 to 1

array([-0.87472758,  1.33083898,  2.03627017,  0.17528735, -1.91493181])

In [31]:
#random.normal
#np.random.normal(loc=10,scale=2,size=(3,5)) # loc = mean and scale = standard deviation
np.random.normal(10,2,(3,5))

array([[10.16544856, 10.70272154, 14.09280148,  9.97204625, 10.67492767],
       [11.00312838, 10.74188095,  6.7295255 ,  9.93377843, 13.22234685],
       [10.31418038,  7.97042708,  7.82411595,  9.54227316,  8.54205236]])

In [34]:
# randint
np.random.randint(1,10,5) # this will create random number between 1 to 10

array([3, 6, 3, 1, 2])

In [36]:
np.random.randint(1,3,(3,5)) # this will create random number between 1 to 10

array([[2, 1, 1, 2, 2],
       [1, 2, 1, 1, 2],
       [1, 1, 2, 2, 2]])

In [44]:
sample_array = np.random.randint(1,10,(3,5))
sample_array

array([[4, 6, 7, 5, 9],
       [5, 5, 6, 8, 9],
       [5, 4, 5, 4, 5]])

In [45]:
sample_array.shape

(3, 5)

In [47]:
sample_array.ndim  # to find the dimension of the array

2

In [48]:
sample_array.dtype

dtype('int64')

In [49]:
sample_array.size

15

In [50]:
sample_array.reshape(5,3)

array([[4, 6, 7],
       [5, 9, 5],
       [5, 6, 8],
       [9, 5, 4],
       [5, 4, 5]])

In [53]:
sample_array = np.arange(1,14)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [54]:
#np.reshape(sample_array,(3,4))  ## cannot reshape array of size 13 into shape (3,4)

ValueError: cannot reshape array of size 13 into shape (3,4)